Unit tests
polaum/rater pull request #1
Opened 2019-02-07 11:24 UTC by polaum

Ignore the tests written. still learning :)

2019-02-07 11:51 UTC, matansh requested changes

2019-02-07 11:51 UTC, matansh commented on raterfunc
> +import pytest
in your unit_tests branch you have a `raterfunc` file and a `raterfunc.py` file.

please remove the `raterfunc` file

2019-02-07 11:54 UTC, polaum commented on raterfunc
> +import pytest
Removed

2019-02-07 11:55 UTC, matansh commented
your repo contains a dir named `.idea`
the `.idea` contains your pycharm configuration.
by pushing this dir in to your repo, all contributors will be forced to use your pycahrm config, and will be able to change your local config when you pull.

luckily for us `git` has a solution for this.

please add a file in the root of your project named `.gitignore`, in this file we list all the files and directories we would like git to ignore in our project.

in the `.gitignore` file add `.idea`, commit and push for the change to take affect

2019-02-07 12:00 UTC, matansh requested changes

2019-02-07 12:00 UTC, matansh commented on raterfunc.py
> +def test_can_consume():
please separate your tests to another file

2019-02-07 12:00 UTC, matansh commented on raterfunc.py
> +def test_can_consume():
usually tests will be located under a dir named `tests`, this dir is usually located on the root of the project

2019-02-07 12:00 UTC, matansh commented on raterfunc.py
> +    print("User not allowed to consume this")
instead of printing this line here you should pass the string `"User not allowed to consume this"` as an input to `raise ConsumptionException`.

2019-02-07 12:00 UTC, matansh commented on raterfunc.py
> +            raise ConsumptionException
```suggestion
            raise ConsumptionException("User not allowed to consume this")
```

2019-02-07 12:21 UTC, matansh requested changes

2019-02-07 12:21 UTC, matansh commented on raterfunc.py
> +        return self.check_limit() >= (self.check_consumption() + desired_added_cons)
what happens when a user has no limit?

please add a test for this scenario

2019-02-07 12:21 UTC, matansh commented on raterfunc.py
> +    def update_consumption(self, added_cons):
splitting the logic in to 2 functions (`can_consume` + `update_consumption`) is very smart and very object oriented!! 

but it means that our user-facing interface is not the most convenient as it could be (in this scenario the users are other developers in our team that will use your rate limiter) 

it seems to me that `can_consume` and `update_consumption` are internal methods and the external interface is a single method called `consume`.

when we create a method that does not implement anything new but just serves a set of logic this is called a factory method.

internal methods that are not part of the external interface are prefixed with 1 underline.
so you will have `_can_consume`, `_update_consumption` and `consume` that uses the first 2

2019-02-07 12:46 UTC, matansh requested changes

2019-02-07 12:46 UTC, matansh commented on raterfunc.py
> +    def check_limit(self):
perfect opertunity to learn `@property`. we will do this change together

2019-02-07 12:46 UTC, matansh commented on raterfunc.py
> +class User:
creating a `User` interface is super good and OO (Object Oriented)!!!

next thing to think about is data persistence between class instances.

as of now i can "cheat" by doing
```
my_user = User(1, 5)
my_user.update_consumption(5)
still_my_user = User(1, 5)
still_my_user.update_consumption(5)
```

in this scenario a user with id `1` consumed twice his allowance

2019-02-07 12:46 UTC, matansh commented on raterfunc.py
> +class User:
please add a test case to cover this

2019-02-07 12:50 UTC, matansh requested changes

2019-02-07 12:50 UTC, matansh commented on raterfunc.py
> +    print("User not allowed to consume this")
```suggestion
    pass
```

2019-02-07 12:55 UTC, matansh commented on raterfunc.py
> +    with pytest.raises(ConsumptionException):
holy shit it's amazing that on your first usage of pytest you picked up on `with pytest.raises`.
if i had a penny for every time i have written in a CR comment "why don't you use `pytest.raises`" we would be rich!

2019-02-08 11:07 UTC, polaum commented on raterfunc.py
> +    def update_consumption(self, added_cons):
Let's talk about this more :)

2019-02-15 16:34 UTC, merged